name: Deploy Dagster Core
on:
  push:
    branches: [main]
    paths:
      - 'terraform/**'

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Terraform Init
        working-directory: ./terraform
        run: |
          terraform init -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=dagster-eks-prod/dev/terraform.tfstate" \
            -backend-config="region=us-west-2" \
            -backend-config="dynamodb_table=terraform-locks"
      - name: Terraform Workspace
        working-directory: ./terraform
        run: terraform workspace select dev || terraform workspace new dev
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -var-file=terraform.tfvars.dev -auto-approve
      - name: Install Cluster Autoscaler
        run: |
          aws eks update-kubeconfig --name my-eks-cluster-dev --region us-west-2
          helm upgrade --install cluster-autoscaler autoscaler/cluster-autoscaler --namespace kube-system \
            --set autoDiscovery.clusterName=my-eks-cluster-dev \
            --set awsRegion=us-west-2
      - name: Display Outputs (Dev)
        working-directory: ./terraform
        run: terraform output

  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Terraform Init
        working-directory: ./terraform
        run: |
          terraform init -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=dagster-eks-prod/prod/terraform.tfstate" \
            -backend-config="region=us-west-2" \
            -backend-config="dynamodb_table=terraform-locks"
      - name: Terraform Workspace
        working-directory: ./terraform
        run: terraform workspace select prod || terraform workspace new prod
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -var-file=terraform.tfvars.prod -auto-approve
      - name: Install Cluster Autoscaler
        run: |
          aws eks update-kubeconfig --name my-eks-cluster-prod --region us-west-2
          helm upgrade --install cluster-autoscaler autoscaler/cluster-autoscaler --namespace kube-system \
            --set autoDiscovery.clusterName=my-eks-cluster-prod \
            --set awsRegion=us-west-2
      - name: Display Outputs (Prod)
        working-directory: ./terraform
        run: terraform output